name: fairness-in-ml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipython
  - jedi
  - jupyter
  - keras==2.1.5
  - matplotlib
  - notebook
  - pandas==0.22.0
  - pip
  - python=3.6
  - scikit-learn==0.19.1
  - seaborn
  - pytorch
